/**
 * 프론트엔드 전체에서 공통으로 사용되는 상수(Constant) 데이터를 정의합니다.
 * 백엔드 데이터베이스의 실제 ID와 매핑되어 사용됩니다.
 */

// 포지션(직무) 매핑 데이터
export const POSITIONS = [
    { id: 1, name: 'Frontend', dbName: 'frontend', icon: '💻' },
    { id: 2, name: 'Backend', dbName: 'backend', icon: '🗄️' },
    { id: 3, name: 'Data/AI', dbName: 'data_ai', icon: '🧠' },
    { id: 4, name: 'Mobile', dbName: 'mobile', icon: '📱' },
    { id: 5, name: 'Infra', dbName: 'infra', icon: '☁️' },
    { id: 6, name: 'Embedded', dbName: 'embedded', icon: '🔧' },
    { id: 7, name: 'Product', dbName: 'product', icon: '📦' },
];

// 기술 스택(Skills) 매핑 데이터
export const SKILLS = [
    { id: 1, name: 'API' },
    { id: 2, name: 'ASP.NET' },
    { id: 3, name: 'AWS' },
    { id: 4, name: 'Ajax' },
    { id: 5, name: 'Android' },
    { id: 6, name: 'Android Studio' },
    { id: 7, name: 'Angular' },
    { id: 8, name: 'Ansible' },
    { id: 9, name: 'Azure' },
    { id: 10, name: 'C' },
    { id: 11, name: 'C#' },
    { id: 12, name: 'C/C++' },
    { id: 13, name: 'CAN' },
    { id: 14, name: 'CSS' },
    { id: 15, name: 'DBMS' },
    { id: 16, name: 'Django' },
    { id: 17, name: 'Docker' },
    { id: 18, name: 'Embedded' },
    { id: 19, name: 'Embedded Linux' },
    { id: 20, name: 'FastAPI' },
    { id: 21, name: 'Flask' },
    { id: 22, name: 'Flutter' },
    { id: 23, name: 'GCP' },
    { id: 24, name: 'Git' },
    { id: 25, name: 'GitHub' },
    { id: 26, name: 'GitLab' },
    { id: 27, name: 'Google Analytics' },
    { id: 28, name: 'Google Optimize' },
    { id: 29, name: 'HTML' },
    { id: 30, name: 'JPA' },
    { id: 31, name: 'JSP' },
    { id: 32, name: 'Java' },
    { id: 33, name: 'JavaScript' },
    { id: 34, name: 'Jenkins' },
    { id: 35, name: 'Kafka' },
    { id: 36, name: 'Kotlin' },
    { id: 37, name: 'Kubernetes' },
    { id: 38, name: 'LLM' },
    { id: 39, name: 'Laravel' },
    { id: 40, name: 'Linux' },
    { id: 41, name: 'MQTT' },
    { id: 42, name: 'MSA' },
    { id: 43, name: 'MSSQL' },
    { id: 44, name: 'MariaDB' },
    { id: 45, name: 'MongoDB' },
    { id: 46, name: 'MyBatis' },
    { id: 47, name: 'MySQL' },
    { id: 48, name: 'NestJS' },
    { id: 49, name: 'Nexacro' },
    { id: 50, name: 'Next.js' },
    { id: 51, name: 'NoSQL' },
    { id: 52, name: 'Node.js' },
    { id: 53, name: 'NumPy' },
    { id: 54, name: 'OpenCV' },
    { id: 55, name: 'Oracle' },
    { id: 56, name: 'PHP' },
    { id: 57, name: 'Pandas' },
    { id: 58, name: 'PostgreSQL' },
    { id: 59, name: 'PyTorch' },
    { id: 60, name: 'Python' },
    { id: 61, name: 'R' },
    { id: 62, name: 'RAG' },
    { id: 63, name: 'RDBMS' },
    { id: 64, name: 'REST API' },
    { id: 65, name: 'ROS' },
    { id: 66, name: 'ROS2' },
    { id: 67, name: 'RTOS' },
    { id: 68, name: 'Raspberry Pi' },
    { id: 69, name: 'React' },
    { id: 70, name: 'React Native' },
    { id: 71, name: 'Redis' },
    { id: 72, name: 'SPSS' },
    { id: 73, name: 'SQL' },
    { id: 74, name: 'SaaS' },
    { id: 75, name: 'Scikit-learn' },
    { id: 76, name: 'Spring' },
    { id: 77, name: 'Spring Batch' },
    { id: 78, name: 'Spring Boot' },
    { id: 79, name: 'Spring MVC' },
    { id: 80, name: 'Spring Security' },
    { id: 81, name: 'Swift' },
    { id: 82, name: 'Tableau' },
    { id: 83, name: 'TensorFlow' },
    { id: 84, name: 'Terraform' },
    { id: 85, name: 'Tibero' },
    { id: 86, name: 'TypeScript' },
    { id: 87, name: 'Unix' },
    { id: 88, name: 'VMware' },
    { id: 89, name: 'Vue.js' },
    { id: 90, name: 'WAS' },
    { id: 91, name: 'WebSquare' },
    { id: 92, name: 'iOS' },
    { id: 93, name: 'jQuery' },
    { id: 94, name: 'Nuxt.js' },
    { id: 95, name: 'Svelte' },
    { id: 96, name: 'Tailwind CSS' },
    { id: 97, name: 'Express.js' },
    { id: 98, name: 'Go' },
    { id: 99, name: 'Rust' },
    { id: 100, name: 'Ruby on Rails' },
    { id: 101, name: 'Elasticsearch' },
    { id: 102, name: 'Firebase' },
    { id: 103, name: 'Supabase' },
    { id: 104, name: 'GraphQL' },
    { id: 105, name: 'gRPC' },
    { id: 106, name: 'GitHub Actions' },
    { id: 107, name: 'Nginx' },
    { id: 108, name: 'RabbitMQ' },
    { id: 109, name: 'WebSocket' },
    { id: 110, name: 'OAuth2' },
    { id: 111, name: 'JWT' },
    { id: 112, name: 'LangChain' },
    { id: 113, name: 'OpenAI API' },
    { id: 114, name: 'Spark' },
    { id: 115, name: 'Airflow' },
    { id: 116, name: 'Prometheus' },
    { id: 117, name: 'Grafana' },
    { id: 118, name: 'Arduino' },
];

// 서비스 도메인(산업 분야) 매핑 데이터
export const DOMAINS = [
    { id: 10001, name: '서비스', dbName: 'service' },
    { id: 10002, name: '금융·은행', dbName: 'finance' },
    { id: 10003, name: 'IT·정보통신', dbName: 'it' },
    { id: 10004, name: '판매·유통', dbName: 'retail' },
    { id: 10005, name: '제조·생산·화학', dbName: 'manufacturing' },
    { id: 10006, name: '건설', dbName: 'construction' },
    { id: 10007, name: '의료·제약', dbName: 'healthcare' },
    { id: 10008, name: '교육', dbName: 'education' },
    { id: 10009, name: '미디어·광고', dbName: 'media' },
    { id: 10010, name: '문화·예술·디자인', dbName: 'culture' },
    { id: 10011, name: '기관·협회', dbName: 'institution' },
];
