// Positions Mapping (Actual Backend IDs)
export const POSITIONS = [
    { id: 1, name: 'Frontend', dbName: 'frontend', icon: '💻' },
    { id: 2, name: 'Backend', dbName: 'backend', icon: '🗄️' },
    { id: 3, name: 'Data/AI', dbName: 'data_ai', icon: '🧠' },
    { id: 4, name: 'Mobile', dbName: 'mobile', icon: '📱' },
    { id: 5, name: 'Infra', dbName: 'infra', icon: '☁️' },
    { id: 6, name: 'Embedded', dbName: 'embedded', icon: '🔧' },
    { id: 7, name: 'Product', dbName: 'product', icon: '📦' },
];

// Skills Mapping (Actual Backend IDs)
export const SKILLS = [
    { id: 1, name: 'React', dbName: 'react' },
    { id: 2, name: 'Next.js', dbName: 'nextjs' },
    { id: 3, name: 'Vue.js', dbName: 'vuejs' },
    { id: 4, name: 'Nuxt.js', dbName: 'nuxtjs' },
    { id: 5, name: 'Angular', dbName: 'angular' },
    { id: 6, name: 'Svelte', dbName: 'svelte' },
    { id: 7, name: 'TypeScript', dbName: 'typescript' },
    { id: 8, name: 'JavaScript', dbName: 'javascript' },
    { id: 9, name: 'Tailwind CSS', dbName: 'tailwind' },
    { id: 10, name: 'React Native', dbName: 'react_native' },
    { id: 11, name: 'Flutter', dbName: 'flutter' },
    { id: 12, name: 'Swift', dbName: 'swift' },
    { id: 13, name: 'Kotlin', dbName: 'kotlin' },
    { id: 14, name: 'Node.js', dbName: 'nodejs' },
    { id: 15, name: 'Spring Boot', dbName: 'spring_boot' },
    { id: 16, name: 'Django', dbName: 'django' },
    { id: 17, name: 'FastAPI', dbName: 'fastapi' },
    { id: 18, name: 'Flask', dbName: 'flask' },
    { id: 19, name: 'NestJS', dbName: 'nestjs' },
    { id: 20, name: 'Express.js', dbName: 'expressjs' },
    { id: 21, name: 'Java', dbName: 'java' },
    { id: 22, name: 'Python', dbName: 'python' },
    { id: 23, name: 'Go', dbName: 'go' },
    { id: 24, name: 'Rust', dbName: 'rust' },
    { id: 25, name: 'C#', dbName: 'csharp' },
    { id: 26, name: 'PHP', dbName: 'php' },
    { id: 27, name: 'Ruby on Rails', dbName: 'rails' },
    { id: 28, name: 'MySQL', dbName: 'mysql' },
    { id: 29, name: 'PostgreSQL', dbName: 'postgresql' },
    { id: 30, name: 'MongoDB', dbName: 'mongodb' },
    { id: 31, name: 'Redis', dbName: 'redis' },
    { id: 32, name: 'Elasticsearch', dbName: 'elasticsearch' },
    { id: 33, name: 'Firebase', dbName: 'firebase' },
    { id: 34, name: 'Supabase', dbName: 'supabase' },
    { id: 35, name: 'GraphQL', dbName: 'graphql' },
    { id: 36, name: 'REST API', dbName: 'rest_api' },
    { id: 37, name: 'gRPC', dbName: 'grpc' },
    { id: 38, name: 'Docker', dbName: 'docker' },
    { id: 39, name: 'Kubernetes', dbName: 'kubernetes' },
    { id: 40, name: 'AWS', dbName: 'aws' },
    { id: 41, name: 'GCP', dbName: 'gcp' },
    { id: 42, name: 'Azure', dbName: 'azure' },
    { id: 43, name: 'GitHub Actions', dbName: 'github_actions' },
    { id: 44, name: 'Jenkins', dbName: 'jenkins' },
    { id: 45, name: 'Terraform', dbName: 'terraform' },
    { id: 46, name: 'Nginx', dbName: 'nginx' },
    { id: 47, name: 'Kafka', dbName: 'kafka' },
    { id: 48, name: 'RabbitMQ', dbName: 'rabbitmq' },
    { id: 49, name: 'WebSocket', dbName: 'websocket' },
    { id: 50, name: 'OAuth2', dbName: 'oauth2' },
    { id: 51, name: 'JWT', dbName: 'jwt' },
    { id: 52, name: 'TensorFlow', dbName: 'tensorflow' },
    { id: 53, name: 'PyTorch', dbName: 'pytorch' },
    { id: 54, name: 'LangChain', dbName: 'langchain' },
    { id: 55, name: 'OpenAI API', dbName: 'openai_api' },
    { id: 56, name: 'Pandas', dbName: 'pandas' },
    { id: 57, name: 'Spark', dbName: 'spark' },
    { id: 58, name: 'Airflow', dbName: 'airflow' },
    { id: 59, name: 'Prometheus', dbName: 'prometheus' },
    { id: 60, name: 'Grafana', dbName: 'grafana' },
    { id: 61, name: 'C/C++', dbName: 'cpp' },
    { id: 62, name: 'RTOS', dbName: 'rtos' },
    { id: 63, name: 'Arduino', dbName: 'arduino' },
    { id: 64, name: 'Raspberry Pi', dbName: 'raspberry_pi' },
    { id: 65, name: 'MQTT', dbName: 'mqtt' }
];

// Dummy Dynamic Company List
export const DUMMY_COMPANIES = [
    { id: 1, name: '삼성' }, { id: 2, name: '네이버' }, { id: 3, name: '카카오' },
    { id: 4, name: '라인' }, { id: 5, name: '쿠팡' }, { id: 6, name: '배달의민족' },
    { id: 7, name: '당근' }, { id: 8, name: '토스' }, { id: 9, name: '구글' }
];
